apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: elastic
spec:
  version: 8.12.0
  count: 1
  config:
    log.level: info
  podTemplate:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              memory: 1Gi  # Reduced from 2Gi to 1Gi
              cpu: 500m    # Reduced from 1 to 0.5
