apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv
spec:
  capacity:
    storage: 5Gi  # Adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-03d679362fa855a98  # Replace with your actual volume ID
    fsType: ext4


















