apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-volume-artifactory-0
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2-csi  # Reference the correct storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-artifactory-postgresql-0
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2-csi  # Reference the correct storage class
