apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::010028775188:role/cert-manager"  # Replace with your IAM Role ARN
