apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: citatech-online-tls
  namespace: default  # or your desired namespace
spec:
  secretName: citatech-online-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: citatech.online
  dnsNames:
    - citatech.online
    - "*.citatech.online"  # if you want a wildcard certificate
