apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Email used for ACME registration
    email: citatech68@gmail.com
    # Name of the ACME server
    server: https://acme-v02.api.letsencrypt.org/directory
    # A secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
