controller:
  config:
    use-forwarded-headers: "true"
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-1:992382613070:certificate/d09ed28c-f8a0-4b49-a0f2-55448eb562a9"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06














# # To output the default helm chat configuration run
# helm show values jfrog/artifactory > nginx-default.yaml


# # Run this command to upgrade the helm release
# helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \                                                                                                [25/09/24 19:02:15]
# --namespace ingress-nginx --create-namespace -f nginx-values.yaml